#!/bin/bash

if [ "$#" != "2" ]; then
    echo \
"Usage: $0 /dev/sdX path/to/config.yml

Refurbishes disk /dev/sdX following config.yml, or fails."
    exit 0
fi

if [ $EUID -gt 500 ]; then
    echo "Error: You are not root."
    exit 1
fi

DISK=$1
CONFIG=$2

BASEDIR="$(dirname $0)/parts"

$BASEDIR/asses_disk $DISK &&
$BASEDIR/wipe_disk  $DISK &&
$BASEDIR/asses_disk $DISK &&
$BASEDIR/copy_image $DISK $CONFIG &&
echo 'All done. Enjoy!' ||
echo 'Error. Disk is NOT ok. Goodbye.'
