#!/bin/sh

export LANG=C
export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true DEBIAN_PRIORITY=critical  # don't ask any questions

# Set the locale (language, formatting, ...) to Slovenian
echo 'sl_SI.UTF-8 UTF-8' >> /etc/locale.gen
locale-gen
update-locale LANG=sl_SI.UTF-8

# Set Slovene keyboard
debconf-set-selections <<END
keyboard-configuration	keyboard-configuration/layout	select	Slovenian
keyboard-configuration	keyboard-configuration/xkb-keymap	select	si
keyboard-configuration	keyboard-configuration/variant	select	Slovenian
keyboard-configuration	keyboard-configuration/ctrl_alt_bksp	boolean	false
keyboard-configuration	keyboard-configuration/modelcode	string	pc105
keyboard-configuration	keyboard-configuration/layoutcode	string	si
END
dpkg-reconfigure keyboard-configuration
